spring:
  application:
    name: store-service
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store
    username: root
    password: root
    initialization-mode: never
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update

server: 
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: ${service-registry.uri:http://127.0.0.1:8761}/eureka
ribbon:
  eureka:
    enabled: true

application:
  master-data-service:
    name: master-data-service
    context-path: /api/masterdataservice/v1
  order-service:
    name: order-service
    context-path: /api/orderservice/v1
  product-service:
    name: product-service
    context-path: /api/productservice/v1
  user-service:
    name: user-service
    context-path: /api/userservice/v1
  support-service:
    name: support-service
    context-path: /api/supportservice/v1
  template-service:
    name: template-service
    context-path: /api/templateservice/v1
  inventory-service:
    name: inventory-service
    context-path: /api/inventory/v1
