spring:
  application:
    name: user-service
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store
    username: root
    password: root
    initialization-mode: never
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
server:
  port: 9004
  servlet: 
    context-path: /api/userservice/v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
ribbon:
  eureka:
    enabled: true
